services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DOCKER_ENVIRONMENT=true
      - APP_DB_URL=${APP_DB_URL}
      - APP_URL=0.0.0.0:8080
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - MG_API_KEY=${MG_API_KEY}
      - MG_SENDER=${MG_SENDER}
      - MG_DOMAIN=${MG_DOMAIN}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: