package constant

const (
	STATUS_SESSION_ACCEPTED = "ACCEPTED"
	STATUS_SESSION_REJECTED = "REJECTED"
	STATUS_SESSION_PENDING  = "PENDING"
)

var STATUS_SESSION_ARRAY = []string{
	STATUS_SESSION_ACCEPTED,
	STATUS_SESSION_REJECTED,
	STATUS_SESSION_PENDING,
}
