definitions:
  dto.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.SignInResponse:
    properties:
      token:
        type: string
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.UpdateUserProfileRequest:
    properties:
      bio:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  dto.UpdateUserRoleRequest:
    properties:
      role:
        enum:
        - ADMIN
        - COORDINATOR
        - USER
        type: string
    required:
    - role
    type: object
  response.JSONResponseModel:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Sign In User
      parameters:
      - description: Sign In Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User Logged In and JWT Token Generated
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  $ref: '#/definitions/dto.SignInResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      summary: Sign In User
      tags:
      - Auth
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign Up New User
      parameters:
      - description: Sign Up Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      summary: Sign Up New User
      tags:
      - Auth
  /api/profile:
    get:
      consumes:
      - application/json
      description: Get Profile User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      security:
      - BearerAuth: []
      summary: Get Profile User
      tags:
      - Profile
    patch:
      consumes:
      - application/json
      description: Update Profile User
      parameters:
      - description: Update Profile User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      security:
      - BearerAuth: []
      summary: Update Profile User
      tags:
      - Profile
  /api/user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User. Only Admin can delete user.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get User Detail
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      security:
      - BearerAuth: []
      summary: Get User Detail
      tags:
      - User
  /api/user/{id}/update-role:
    put:
      consumes:
      - application/json
      description: Update Role User. Only Admin can update role user.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User Role
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONResponseModel'
            - properties:
                data:
                  type: object
              type: object
      security:
      - BearerAuth: []
      summary: Update Role User
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
